### ISSUE TITLE
Need to change name of project

### ISSUE THREAD

**Issue by iLoveTux** [iLoveTux/aina#4]
I am looking for suggestions about new names for this project, I would like to publish to PyPI but flume is taken and I cannot come up with a decent name.

**Comment by iLoveTux** [comment]
I have changed the name to "aina" as a recursive acronym for "Aina is not Awk". This makes sense to two people who have been working on this for quite a while. I am still looking for suggestions for a new name as it does not really even resemble Awk anymore.

**Comment by iLoveTux** [comment]
Just to clarify the reason for the rename is just to get this listed on PyPI. which it is now, you can simply `pip install aina` to get the latest stable version.

**Comment by jayvdb** [comment]
Finished?

**Comment by iLoveTux** [comment]
Thanks for your interest in this project. I haven't touched this code in a while, but I think I will come in and clean up a few things.

This is done. `pip install aina` should just work so I will close this issue.
