### ISSUE TITLE
Supported versions?

### ISSUE THREAD

**Issue by jayvdb** [iLoveTux/aina#5]
Travis has 3.5+, but setup.py lists Python 2.7

I found Python 3.4 failed with `AttributeError: 'PosixPath' object has no attribute 'write_text'` when packaging for openSUSE

https://build.opensuse.org/package/show/home:jayvdb:py-new/python-aina

**Comment by jayvdb** [comment]
It shouldnt be much effort to add backwards compatibility, using libraries which provide that, if you wanted it.  Otherwise, just remove 2.7 and 3.4 from setup.py and forget about all those problems ;-)

**Comment by iLoveTux** [comment]
Thanks for taking the time to submit this issue.

3.5+ is supported. I will look into adding backwards compatibility, but with only 7 months left until Python 2 is EOL I will probably only target 3.4 and 3.3, but I honestly don't know if the effort there will be worth it.

Short term I will remove the unsupported versions from setup.py.

**Comment by iLoveTux** [comment]
This is done and the package has been updated on Pypi. The proper supported versions now displayed so I am closing this issue.

Thanks again for bringing this to my attention!

**Comment by jayvdb** [comment]
Thanks @iLoveTux 

Now submitted to the main openSUSE python area https://build.opensuse.org/request/show/703693

https://github.com/iLoveTux/aina/releases doesnt have 0.1.3 yet.

**Comment by iLoveTux** [comment]
Thanks! Done.
If you're not careful you just might make me a better maintainer.
